name: main
on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node & Install Yarn
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm install -g yarn

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install packages
        run: yarn install

      - name: Build JS
        run: yarn build

      - name: Add, commit, and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add --force tsundoku/blueprints/ux/static/js/*.js
          git diff-index --quiet HEAD || git commit -m "Autobuild JS"
          git push --force
