name: main
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node & Install Yarn
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm install -g yarn

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install packages
        run: yarn install

      - name: Build JS
        run: yarn build

      - uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: Apply built JavaScript
            file_pattern: *.js